PAYPAL_USERNAME = 'emailaddress'
PAYPAL_NAME = 'My Name'
PAYPAL_PASSWORD = 'mypassword'
EXPORT_DIRECTORY = '/home/myname/'
CACHE_DIRECTORY = '/home/myname/'
START_DATE = "11/08/2013"
END_DATE = "08/10/2014"
START_AT_PAGE = 0
